// <auto-generated />
namespace HotelCrown.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Mig7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mig7));
        
        string IMigrationMetadata.Id
        {
            get { return "202204112354597_Mig7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
